services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: subsidii
      POSTGRES_USER: subsidii
      POSTGRES_PASSWORD: subsidii
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U subsidii -d subsidii"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bot:
    build: bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}

  api:
    build: api
    ports:
      - 3000:8000
    environment:
      DATABASE_URL: postgresql+asyncpg://subsidii:subsidii@postgres:5432/subsidii
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
