name: Deploy to VPS

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1
              with:
                  capture_stdout: true
                  host: ${{secrets.VPS_HOST}}
                  username: ${{secrets.VPS_USER}}
                  key: ${{secrets.SSH_PRIVATE_KEY}}
                  script: |
                      set -euo pipefail

                      export PNPM_HOME="/home/deploy/.local/share/pnpm"
                      export PATH="$PNPM_HOME/bin:$PATH"

                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

                      pnpm --version
                      node --version

                      cd /opt/max-2026-pro-subsidii
                      git pull origin main

                      export COMPOSE_FILE=prod.docker-compose.yaml
                      docker compose up --build -d

                      cd web
                      pnpm install --frozen-lockfile
                      pnpm build
                      cp -r dist/* /var/www/${{secrets.SITE_DOMAIN}}/
